multiple_instances: multiple_instances.cpp simple_lighting.vert simple_lighting.frag
	g++ `pkg-config --cflags glfw3 glew` -o multiple_instances multiple_instances.cpp `pkg-config --static --libs glfw3 glew`

