multiple_instances: multiple_instances.cpp simple_lighting.vert simple_lighting.frag
	g++ `pkg-config --cflags glfw3 glew` -o multiple_instances multiple_instances.cpp `pkg-config --static --libs glfw3 glew`

multiple_instances_alt: multiple_instances_alt.cpp simple_lighting.vert simple_lighting.frag
	g++ `pkg-config --cflags glfw3 glew` -o multiple_instances_alt multiple_instances_alt.cpp `pkg-config --static --libs glfw3 glew`

